version: '3.9'

services:
  app-spring:
    image: study-project-app-spring:0.0.1
    ports:
      - "8080:8080"
    environment:
      DB_TYPE_PROD: "psql"
      MGRTASK_HOST: "psql"
      MGRTASK_PORT: 5432
      MGRTASK_DB: "taskManager"
      MGRTASK_USER: "postgres"
      MGRTASK_PASS: "taskManager-pass"
      THC_PATH: "/actuator/health"
    depends_on:
      psql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/workspace/health-check"]

  psql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      PGUSER: "postgres"
      POSTGRES_PASSWORD: "taskManager-pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "taskManager"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: "ok-migration-pg:0.1.0"
    environment:
      LIQUIBASE_URL:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://psql:5432/taskManager
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: "taskManager-pass"
      LIQUIBASE_LIQUIBASE_SCHEMA_NAME: public
    #      tableName: tasks

    depends_on:
      psql:
        condition: service_healthy
